# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-08 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20170602_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/%Y/%m/%d'),
        ),
    ]
