# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-07 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20170601_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncomment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_comment', to='questions.Question'),
        ),
    ]
